[package]
name = "neon-gcc"
version = "0.1.0"
build = "build.rs"

[lib]
name = "neongcc"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.15"
gcc = "0.3"

[dependencies]
neon = "0.1.15"
